# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Bio
    url: /
    weight: 100
  - name: Experience
    url: /#experience
    weight: 150
  - name: Future_goal
    url: /#future_goal
    weight: 200
  - name: Projects
    url: projects/
    weight: 250
  - name: Skill
    identifier: skill
    weight: 300
  - name: Contact
    url: contact/
    weight: 350
  - name: Framework
    identifier: framework
    parent: skill
    url: framework/
    weight: 100
  - name: Programming_language
    identifier: programming_language
    parent: skill
    url: programming_language/
    weight: 200
